
import useStore from 'src/store'
import axios from 'axios'
import * as bchOauth from './bch-oauth.js'


// Create backend using axios
export const backend = axios.create({
  baseURL: process.env.AUCTION_HUB_API
})

/***
  NOTES:
  - Check repository auction-hub README for api urls
  - date formats: new Date().toISOString(),
  * @param pathname = pathname in url for api 
  * @param id = could be pk, lot, etc. (specifically if we're referring to getting one item, so don't put anything if fetching multiple items)
  * @param method = ['get', 'post', 'put', 'delete']; default is get 
  * @param payload = object containing the data for post/put (not needed for get/delete)
*/
export async function callAPI(pathname, id=null, method="get", payload=null, args) {
  const store = useStore()
  
  // Add base api url
  let apiURL = `${bchOauth.baseURL}/`

  if (Array.isArray(pathname)) { 
    // Other list apis
    for (let i = 0; i < pathname.length; i++) {
      apiURL += `${pathname[i]}/`

      // If an id exists, add it to the url
      if(id?.[i] !== null) apiURL += `${id[i]}/`
    }
  } else { // GENERAL FORMAT
    apiURL += `${pathname}/` // list, post

    if (id !== null) { 
      apiURL += `${id}/`  // retrieve
      switch(method) {
        case "put":
        case "patch":
          apiURL += `update/` // update/patch
          break
        case "delete":
          apiURL += `delete/` // delete
      }
    }
  } 
  // Print entire url (for testing/debugging)
  console.log(apiURL) 

  // Init return data
  let success = false;
  let data = null;
  let errorMessage = null;

  try {
    const headers = await bchOauth.getAuthHeaders()
    const response = 
      (method === "get") ? await backend.get(apiURL, { headers }) : 
      (method === "post") ? await backend.post(apiURL, payload, { headers }) :
      (method === "put") ? await backend.put(apiURL, payload, { headers }) :
      (method === "patch") ? await backend.patch(apiURL, payload, { headers }) :
    await backend.delete(apiURL, { headers }) 

    // Update apiCall return data
    data = response.data
    success = true

    // Set no network error
    store.commit('auction/setHasNetworkError', false)
  } catch (error) {
    if (error.response) {
      // Errors where a response was generated from the server
      switch(error.response?.status){
        case 404:
          errorMessage = 'No matching data found.'
          break
        case 403: 
          errorMessage = 'Forbidden access.'
          break
        case 401:
          errorMessage = 'Unauthorized access.'
          break
        default:
          errorMessage = 'An error occurred.'
      }
      store.commit('auction/setHasNetworkError', false)
      
    } else if (error.request) { 
      // No response was generated by the server (likely couldn't connect to API)
      errorMessage = 'Unable to connect to the server.'
      store.commit('auction/setHasNetworkError', true)
    } else {
      // Something unexpected
      errorMessage = 'Unexpected error occurred.'
      store.commit('auction/setHasNetworkError', false)
    }

    // Update apiCall return data
    success = false
  }

  return {
    success,
    data,
    error: errorMessage
  } 
}





