<template>
  <div id="registration-container">
    <div class="row">
      <div class="col pt-brand">
        <img src="~/assets/paytaca_logo.png" height="60">
        <p class="pt-brandname">Paytaca</p>
      </div>
    </div>
    <div class="row pt-wallet q-mt-sm" v-if="mnemonic.length === 0 && importSeedPhrase === false">
      <div class="col-12 q-mt-md q-px-lg q-py-none">
        <div class="row">
          <div class="col-12 q-py-sm">
            <q-btn push class="full-width pt-btn-wallet" @click="createWallets" label="Create New Wallet" rounded />
          </div>
          <div class="col-12 text-center q-py-sm">
            <p class="q-my-none q-py-none" style="font-size: 14px; color: #2E73D2;">OR</p>
          </div>
          <div class="col-12 q-py-sm">
            <q-btn push class="full-width pt-btn-wallet" @click="() => { importSeedPhrase = true }" label="Restore from Seed Phrase" rounded />
          </div>
        </div>
      </div>
    </div>
    <div class="row pt-wallet q-mt-sm" v-if="importSeedPhrase && mnemonic.length === 0">
      <div class="col-12 q-px-lg">
        <p style="text-align: center; font-size: 16px;">Restore your Paytaca wallet from its mnemonic backup phrase.</p>
        <textarea class="form-textarea q-mt-xs pt-input" rows="4" v-model="seedPhraseBackup"></textarea>
        <p style="color: red;">Note: Only seed phrases generated by a Paytaca wallet can be imported at the moment. Seed phrases generated by other wallets won't work.</p>
        <q-btn push class="full-width pt-btn-wallet q-mt-sm" @click="createWallets" label="Restore Wallet" rounded />
      </div>
    </div>

    <div class="row" v-if="mnemonic.length > 0">
      <div class="pt-get-started q-mt-sm q-pa-lg">

        <template v-if="steps === totalSteps">
          <h5 class="q-ma-none get-started-text">Mnemonic Backup Phrase</h5>
          <p v-if="importSeedPhrase" class="dim-text" style="margin-top: 10px;">
            Double check if this matches your mnemonic backup phrase.
          </p>
          <p v-else class="dim-text" style="margin-top: 10px;">
            Write on paper or take a screenshot and keep it somewhere safe.
          </p>
        </template>
        <p class="dim-text" style="text-align: center;" v-else>{{ importSeedPhrase ? 'Restoring' : 'Creating' }} your wallet...</p>

        <div class="row" id="mnemonic">
          <div class="col q-mt-sm" v-if="steps === totalSteps">
            <ul>
              <li v-for="(word, index) in mnemonic.split(' ')" :key="'word-' + index">
                <pre>{{ index + 1 }}</pre><span>{{ word }}</span>
              </li>
            </ul>
          </div>
          <div class="col q-mt-sm" v-if="steps < totalSteps" style="text-align: center;">
            <loader></loader>
          </div>
        </div>
        <div class="row" v-if="steps === totalSteps">
          <q-btn push class="full-width pt-btn-wallet" @click="choosePreferedSecurity" label="Continue" rounded />
        </div>
      </div>
    </div>

    <securityOptionDialog :security-option-dialog-status="securityOptionDialogStatus" v-on:preferredSecurity="setPreferredSecurity" />
    <pinDialog :pin-dialog-action="pinDialogAction" v-on:nextAction="executeActionTaken" />

  </div>
</template>

<script>
import { Wallet, storeMnemonic, generateMnemonic } from '../../wallet'
import Loader from '../../components/loader'
import pinDialog from '../../components/pin'
import securityOptionDialog from '../../components/authOption'
import { NativeBiometric } from 'capacitor-native-biometric'

export default {
  name: 'registration-accounts',
  components: { Loader, pinDialog, securityOptionDialog },
  data () {
    return {
      importSeedPhrase: false,
      seedPhraseBackup: null,
      mnemonic: '',
      steps: 0,
      totalSteps: 5,
      seedInput: true,
      pinDialogAction: '',
      pin: '',
      counter: 0,
      validationMsg: '',
      pinKeys: [{ key: '' }, { key: '' }, { key: '' }, { key: '' }, { key: '' }, { key: '' }],
      countKeys: 0,
      securityOptionDialogStatus: 'dismiss'
    }
  },
  methods: {
    continueToDashboard () {
      const vm = this

      this.$store.dispatch('global/updateOnboardingStep', 1).then(function () {
        vm.$router.push('/')
      })
    },
    async createWallets () {
      const vm = this

      // Create mnemonic seed, encrypt, and store
      if (vm.importSeedPhrase) {
        this.mnemonic = await storeMnemonic(this.seedPhraseBackup)
      } else {
        this.mnemonic = await generateMnemonic()
      }
      vm.steps += 1

      const wallet = new Wallet(this.mnemonic)
      console.log('New address: ', wallet.BCH.getNewAddressSet)

      wallet.BCH.getNewAddressSet(0).then(function (addresses) {
        console.log('Addresses: ', addresses)
        vm.$store.commit('global/updateWallet', {
          type: 'bch',
          walletHash: wallet.BCH.walletHash,
          derivationPath: wallet.BCH.derivationPath,
          lastAddress: addresses !== null ? addresses.receiving : '',
          lastChangeAddress: addresses !== null ? addresses.change : '',
          lastAddressIndex: 0
        })
        vm.steps += 1
      })

      wallet.BCH.getXPubKey().then(function (xpub) {
        vm.$store.commit('global/updateXPubKey', {
          type: 'bch',
          xPubKey: xpub
        })
        vm.steps += 1
      })

      wallet.SLP.getNewAddressSet(0).then(function (addresses) {
        vm.$store.commit('global/updateWallet', {
          type: 'slp',
          walletHash: wallet.SLP.walletHash,
          derivationPath: wallet.SLP.derivationPath,
          lastAddress: addresses !== null ? addresses.receiving : '',
          lastChangeAddress: addresses !== null ? addresses.change : '',
          lastAddressIndex: 0
        })
        vm.steps += 1
      })

      wallet.SLP.getXPubKey().then(function (xpub) {
        vm.$store.commit('global/updateXPubKey', {
          type: 'slp',
          xPubKey: xpub
        })
        vm.steps += 1
      })
    },
    choosePreferedSecurity () {
      this.checkFingerprintAuthEnabled()
    },
    checkFingerprintAuthEnabled () {
      NativeBiometric.isAvailable()
        .then(result => {
          if (result.isAvailable !== false) {
            this.securityOptionDialogStatus = 'show'
          } else {
            this.pinDialogAction = 'SET UP'
          }
        },
        (error) => {
          this.pinDialogAction = 'SET UP'
          console.log('Implementation error: ', error)
        })
    },
    verifyBiometric () {
      // Authenticate using biometrics before logging the user in
      NativeBiometric.verifyIdentity({
        reason: 'For easy log in',
        title: 'Security Authentication',
        subtitle: 'Verify your account using fingerprint.',
        description: ''
      })
        .then(() => {
          // Authentication successful
          console.log('Successful fingerprint credential')
          this.continueToDashboard()
        },
        (error) => {
          // Failed to authenticate
          console.log('Verification error: ', error)
          if (error.message.includes('Cancel') || error.message.includes('Authentication cancelled')) {
            console.log('Ignore')
          } else {
            this.verifyBiometric()
          }
        }
        )
    },
    setPreferredSecurity (auth) {
      this.$q.localStorage.set('preferredSecurity', auth)
      if (auth === 'pin') {
        this.pinDialogAction = 'SET UP'
      } else {
        this.verifyBiometric()
      }
    },
    executeActionTaken (action) {
      const vm = this
      if (action === 'proceed') {
        vm.continueToDashboard()
      } else {
        vm.pinDialogAction = ''
      }
    }
  }
}
</script>

<style>
.pt-wallet {
  width: 100%;
  min-height: calc(100vh - 152px);
  border-top-left-radius: 22px;
  border-top-right-radius: 22px;
  background-color: #F9F8FF;
  padding-top: 28px !important;
}
ul {
  list-style: none;
  display: block;
  margin-left: -40px;
  text-align: justify;
}
ul li {
  display: inline-block;
  font-size: 18px;
  padding: 10px;
}
li span {
  background:#AAB2E9;
  padding: 5px 15px;
  border-radius: 20px;
  color: #fff;
}
li pre {
  display: inline;
  color: #D36EE1;
  padding-right: 5px;
}
.font-lg {
  font-size: 20px;
}
.form-textarea {
  width: 100%;
  border-radius: 18px;
  border: 1px solid #008BF1;
  outline: 0;
  padding-left: 14px;
  padding-top: 10px;
}
.form-textarea:focus {
  border-color: #89BFF4;
  box-shadow: 0px 0px 2px 2px rgba(137, 191, 244, .5);
}
.dim-text {
  color: #8F8CB8;
}
.pt-btn-wallet {
  color: #fff;
  height: 40px;
  background-color: #2E73D2;
}
</style>
