name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your version

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run start & # change this if you use a different command
        env:
          CI: true

      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@master
        with:
          url: 'http://localhost:9000'
          timeout: 60

      - name: Run Cypress tests
        run: npm test
